apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-ui
  template:
    metadata:
      labels:
        app: front-ui
    spec:
      containers:
        - name: front-ui
          image: shiro19000/info910-front-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"