apiVersion: v1
kind: Service
metadata:
  name: front-ui-service
spec:
  type: NodePort
  ports:
    - name: front-ui-port
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: front-ui